# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ness_soft
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ness_soft
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/db/init:/docker-entrypoint-initdb.d:ro
